# Generated by Django 4.2.7 on 2023-12-01 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason_for_visit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('doctors_id', models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('id_no', models.IntegerField(unique=True)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('hepatology', 'Hepatology'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology')], max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientsModel',
            fields=[
                ('patient_id', models.CharField(blank=True, default='', max_length=7, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('residence', models.CharField(max_length=100)),
                ('id_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('color', models.CharField(default='white', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReportModel',
            fields=[
                ('report_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 11, 30, 20, 53, 15, 316213))),
                ('report', models.TextField(default='', null=True)),
                ('doctors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.doctorsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.patientsmodel')),
            ],
        ),
    ]
