# Generated by Django 4.2.7 on 2023-11-29 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 18, 43, 13, 753284)),
        ),
    ]
