# Generated by Django 4.2.7 on 2024-04-10 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('hepatology', 'Hepatology'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology')], max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=200)),
                ('hospital_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('image', models.ImageField(upload_to='patients/')),
                ('contact', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 12, 25, 3, 448655)),
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2024, 4, 10, 12, 25, 3, 446784))),
                ('title', models.CharField(max_length=255)),
                ('drugs', models.TextField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.hospital'),
        ),
    ]
