# Generated by Django 4.2.7 on 2023-11-29 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_alter_doctorsmodel_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='doctors_id',
            field=models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 12, 58, 42, 689682)),
        ),
    ]
