# Generated by Django 4.2.7 on 2024-04-10 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_alter_medicalreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 15, 8, 14, 701682)),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 15, 8, 14, 703185)),
        ),
    ]
