# Generated by Django 4.2.7 on 2023-11-29 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_alter_doctorsmodel_doctors_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsmodel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 13, 41, 10, 431955)),
        ),
    ]
