# Generated by Django 4.2.7 on 2024-04-10 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 21, 41, 12, 301222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 21, 41, 12, 303063)),
        ),
    ]
