# Generated by Django 4.2.7 on 2024-04-10 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0006_alter_hospital_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 21, 43, 36, 516221, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 21, 43, 36, 517972)),
        ),
    ]
