# Generated by Django 4.2.7 on 2023-11-30 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0006_appointment_alter_doctorsmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 30, 14, 36, 6, 659043)),
        ),
    ]
