# Generated by Django 4.2.7 on 2023-11-30 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0009_alter_medicalreportmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreportmodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 30, 17, 17, 2, 981526)),
        ),
    ]
