# Generated by Django 4.2.7 on 2024-04-19 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0010_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 20, 13, 10, 718326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 13, 13, 10, 723149)),
        ),
    ]
