# Generated by Django 4.2.7 on 2024-04-19 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0011_alter_medicalreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 20, 17, 43, 81177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 13, 17, 43, 81177)),
        ),
    ]
