# Generated by Django 4.2.7 on 2024-04-29 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0013_alter_doctor_image_alter_medicalreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 9, 49, 56, 183732, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalreportmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 9, 49, 56, 184931)),
        ),
    ]
